### ISSUE TITLE
Facebook profile api more data

### ISSUE THREAD

**Issue by tg44** [TeamWanari/tutelar#1]
On the facebook auth integration, we call the `https://graph.facebook.com/me` api. Based on the [api explorer](https://developers.facebook.com/tools/explorer/) and the [permissions documentation](https://developers.facebook.com/docs/facebook-login/permissions/#reference-default), we should return all the default fields, and if the email added to the scope the email too.

Also, modify the docs respectively!

**Comment by dmitraver** [comment]
It looks like its already done properly, at least in a code I see that 
``
case class ProfileData(id: String, data: JsObject)
``

has data as JsObject, which probably already has all fields inside. Can you please point if this is the case? @tg44

**Comment by dmitraver** [comment]
thx @tg44 for checking that out, I would check their doc and adjust the code accordingly.

**Comment by dmitraver** [comment]
@tg44 checked their api and it looks like you can't pass any params there https://developers.facebook.com/docs/graph-api/reference/user/.

Also I checked the documentation https://developers.facebook.com/docs/facebook-login/permissions/#reference-default again and it feels like these fields can be seen by default without any extra grant permissions. Under them there are some extra grants that need to be specified (like getting users friends.)

**Comment by dmitraver** [comment]
I could update api to the newest version if needed

**Comment by tg44** [comment]
I started with this: https://developers.facebook.com/tools/explorer/
If you check the url, and experiment with it a bit, I still think that you need to add the "scope" values as a field: `?fields=id,name,address,gender` Try out with getting a token with gender and address rights, and try to call the `me` without fields and after that try it with added fields.

I think the correct implementation would get all the fields that we have rights. (And we claim rights as scopes, so basicly we need to add the "scope" list as a "fields" list.)

But it would be even better if you could try out this from manual/automated tests before further implementations.

**Comment by dmitraver** [comment]
@tg44 I did some tests with API explorer and found that I was actually correct in my assumption. These fields require no permission (you can't even set that). If you just call me/ you get only "name" and "id". If you want all of the default fieds
``
id
first_name
last_name
middle_name
name
name_format
picture
short_name
``

with the same names returned you need to specify them in me?fields... but you need no extra permission for them. 
Should I then add them to /me path and update api version?
