### ISSUE TITLE
Hook service support custom header auth

### ISSUE THREAD

**Issue by Ksisu** [TeamWanari/tutelar#30]
Tutelar optionally calls an other application when a user register/login/removed etc. This calls are implemented in the `HookService`. The other application maybe require authenticating somehow. Currently we support `Basic` and `Escher` authentication.

The issue is implementing a third often used auth method: custom header with secret token.

hints:
- it's basically same as the `Basic` auth
- conf see `application.conf:143` `com.wanari.tutelar.core.impl.ConfigServiceImpl#getHookConfig` `com.wanari.tutelar.core.HookService.BasicAuthConfig`
- implement the auth method see `com.wanari.tutelar.core.impl.HookServiceImpl#authenticator`
- write tests, see `com.wanari.tutelar.core.impl.HookServiceSpec`

**Comment by l4ty4k** [comment]
Hey, I'd like to pick this issue.

**Comment by pogiedoge** [comment]
Pls, assign this issue to me.
