### ISSUE TITLE
MemoryDatabaseService should be thread-safe

### ISSUE THREAD

**Issue by Ksisu** [TeamWanari/tutelar#4]
The `com.wanari.tutelar.core.impl.database.MemoryDatabaseService` currently use `import scala.collection.mutable.Map` for storing data. It should be used a thread-safe collection.

**Comment by dmitraver** [comment]
hi, I could pick this one

**Comment by Ksisu** [comment]
thank you very much!

**Comment by dmitraver** [comment]
@Ksisu happy to help :)
