### ISSUE TITLE
Add providers field to shortTerm token

### ISSUE THREAD

**Issue by Ksisu** [TeamWanari/tutelar#42]
Add a new field `providers` to `shortTerm` token. This field should contain those providers name which used to login. Currently contain only one provider (which used to login).

eg. token data after login with facebook:
```
{ "id": "user-id-1", "providers": ["facebook"] }
```

Hints:
- see `com.wanari.tutelar.core.impl.AuthServiceImpl#createTokenData`
- for the 'big picture' see [MultiFactorAuth](https://github.com/TeamWanari/tutelar/wiki/Multi-Factor-Auth)

**Comment by ilysia** [comment]
I'm interested.
