### ISSUE TITLE
RabbitMQ hosts config from environment variable

### ISSUE THREAD

**Issue by Ksisu** [TeamWanari/tutelar#8]
The RabbitMQ client is using the `application.conf`. Most of the settings has environment variable option eg `RABBITMQ_VIRTUAL_HOST`. The problem is: we cant use directly for the `hosts` because it is an array.
```
op-rabbit {
  [...]
  connection {
    virtual-host = "/"
    virtual-host = ${?RABBITMQ_VIRTUAL_HOST}
    hosts = ["127.0.0.1"] # TODO from env
    [...]
```

**Comment by tg44** [comment]
The goto approach in this case is usually a list separated with colons, and translated in code.
Sth like:
`hostsAsString = "127.0.0.1,127.0.0.2,127.0.0.3"`
and in code
```
val hosts = hostsAsString.split(",").map(_.trim).filter(_ != "")
if(hosts.nonEmpty) {
  //override the conf hosts value with our computed hosts value
}
```

**Comment by Ksisu** [comment]
`op-rabbit` was dropped. `akka-stream-alpakka-amqp` is used.
